name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Download OpenHIM compose file
      run: curl https://raw.githubusercontent.com/jembi/openhim-core-js/v5.4.2/infrastructure/docker-compose.yml -o docker-compose.yml
    - name: Start OpenHIM stack
      run: |
        docker-compose up -d
        sleep 15
    - name: Run integration tests
      run: npm run test:integration
    - name: Run linting
      run: npm run test:lint
